USE [EMPLOYEE]
GO

/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 03-04-2024 21:46:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLOYEE](
	[EMP_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMP_NAME] [varchar](50) NOT NULL,
	[EMP_DESCRIPTION] [varchar](50) NOT NULL,
	[EMP_AGE] [int] NOT NULL,
	[EMP_SALARY] [bigint] NOT NULL,
	[EMP_JOINDATE] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EMP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


